Always put files in $HOME/sslpair

diff --git a/ssl-pairgen b/ssl-pairgen
--- a/ssl-pairgen
+++ b/ssl-pairgen
@@ -5,10 +5,58 @@
 # It will:
 # - Create a temporary Certificate Authority (CA) certificate.
 # - Generate a user certificate signed by this CA.
-# - Output the following files:
+# - Output the following files in $HOME/sslpair:
 #   - <username>-ca.crt: The CA certificate.
 #   - <username>.pem: The user's certificate.
 #   - <username>.p12: A PKCS#12 package containing the user's key and certificate, encrypted with a passphrase.
+
+# Exit immediately if a command exits with a non-zero status
+set -e
+
+# Function to print error message and exit
+function error_exit {
+    echo "Error: $1" >&2
+    exit 1
+}
+
+# Function to prompt the user for removing an existing directory
+function handle_existing_directory {
+    local dir="$1"
+    echo "Directory '$dir' already exists."
+    while true; do
+        read -p "Do you want to remove it and continue? (yes/no): " yn
+        case $yn in
+            [Yy][Ee][Ss]|[Yy])
+                rm -rf "$dir"
+                echo "Removed existing directory '$dir'."
+                break
+                ;;
+            [Nn][Oo]|[Nn])
+                echo "Exiting without making changes."
+                exit 0
+                ;;
+            *)
+                echo "Please answer yes or no."
+                ;;
+        esac
+    done
+}
+
+# Define the destination directory
+SSLPAIR_DIR="$HOME/sslpair"
+
+# Check if the destination directory exists
+if [ -d "$SSLPAIR_DIR" ]; then
+    handle_existing_directory "$SSLPAIR_DIR"
+fi
+
+# Create the destination directory
+mkdir -p "$SSLPAIR_DIR"
+echo "Created directory '$SSLPAIR_DIR'."
+echo
+
+# Change to the destination directory
+cd "$SSLPAIR_DIR"
 
 echo "Welcome to the SSL Key Pair Generator Script"
 echo ""
@@ -35,27 +83,6 @@ USER_NAME=$(echo "$USER_NAME" | tr A-Z a-z)
 CERT_FILE="${USER_NAME}-ca.crt"
 USER_CERT_FILE="${USER_NAME}.pem"
 P12_FILE="${USER_NAME}.p12"
-
-# Check if output files already exist
-OUTPUT_FILES=("${CERT_FILE}" "${USER_CERT_FILE}" "${P12_FILE}")
-EXISTING_FILES=()
-
-for FILE in "${OUTPUT_FILES[@]}"; do
-    if [[ -e "$FILE" ]]; then
-        EXISTING_FILES+=("$FILE")
-    fi
-done
-
-if [[ ${#EXISTING_FILES[@]} -gt 0 ]]; then
-    echo ""
-    echo "Error: The following file(s) already exist in the current directory:"
-    for FILE in "${EXISTING_FILES[@]}"; do
-        echo " - $FILE"
-    done
-    echo ""
-    echo "Please remove the existing file(s), or run the script in a new empty directory"
-    exit 1
-fi
 
 echo ""
 echo "Generating CA and user keys and certificates..."
@@ -96,6 +123,7 @@ echo "Now, you will be prompted to create a passphrase to encrypt your PKCS#12 p
 echo "Please remember this passphrase, as you will need it to import the certificate into your browser or applications."
 echo ""
 
+# Ensure that OpenSSL prompts for the passphrase interactively
 openssl pkcs12 -export -out "${P12_FILE}" \
   -inkey user.key -in user.crt -certfile "${CERT_FILE}" \
   -name "${USER_NAME}" \
@@ -111,10 +139,12 @@ rm ca.key user.key user.csr user.crt "${EXTENSIONS}"
 echo ""
 echo "Certificate generation complete!"
 echo ""
-echo "The following files have been created in the current directory:"
+echo "The following files have been created in '$SSLPAIR_DIR':"
 echo "1. ${CERT_FILE} - Your private CA certificate."
 echo "2. ${USER_CERT_FILE} - Your user certificate in PEM format."
 echo "3. ${P12_FILE} - A PKCS#12 package containing your key and certificate (encrypted with your passphrase)."
 echo ""
 echo "You can now use these certificates for mTLS authentication to access private resources."
 echo "Please import the '${P12_FILE}' file into your browser, using the passphrase you provided."
+
+exit 0
